version: '3.8'

services:
  consul:
    image: hashicorp/consul
    container_name: consul-server
    ports:
      - "8500:8500" # UI do Consul
      - "8600:8600/udp" # DNS do Consul
    command: "agent -dev -client=0.0.0.0"
